apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-api
  template:
    metadata:
      labels:
        app: spring-api
    spec:
      containers:
        - name: spring-api-container
          image: jv031969/spring-security:latest
          ports:
            - containerPort: 8083
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
